### ISSUE TITLE
NPE thrown when using `deathchest list abc`

### ISSUE THREAD

**Issue by jiegec** [tim-savage/SavageDeathChest#52] opened 2019-02-06 11:17 UTC
Using deathchest 1.13.3, original stacktrace:
```
>deathchest list abc
[19:15:34 WARN]: Unexpected exception while parsing console command "deathchest list abc"
org.bukkit.command.CommandException: Unhandled exception executing command 'deathchest' in plugin SavageDeathChest v1.13.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.winterhaven_mc.deathchest.commands.CommandManager.listCommand(CommandManager.java:337) ~[?:?]
        at com.winterhaven_mc.deathchest.commands.CommandManager.onCommand(CommandManager.java:141) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-b0f4c22-2ced023]
        ... 8 more
```

**Comment by tim-savage** [comment] 2019-02-09 21:09
I am unable to reproduce this on my test server. Could you give me some more information regarding the circumstances under which this occured?

- Is this happening when the player ('abc') does not exist (has never logged into this server), or an existing player?
- If it's an existing player, do they currently have any deployed chests, or no chests?
- If no chests, did they previously have a chest?
- Is the player currently logged in?

Thanks for the report, I'd like to eliminate any and all bugs that I can in the plugin.

**Comment by jiegec** [comment] 2019-02-10 02:21
In fact, the input is not 'abc', but real players. I have tested the following circumstances:
1. Player does not exist.
2. Existing player with deployed chests, and currently logged in.

**Comment by tim-savage** [comment] 2019-02-11 20:44
Ok, I'm going to close the issue then, but if it crops up again, please open another ticket.

**Closed by tim-savage** 2019-02-11 20:44 UTC
