### ISSUE TITLE
Doubles items in 1.14.2

### ISSUE THREAD

**Issue by OverDhill** [tim-savage/SavageDeathChest#59] opened 2019-06-17 15:36 UTC
When used in 1.14.2 the chest has your items as well as a duplicate set laying around the outside of the chest when you die.

Needs updating for 1.14.2

**Comment by AryToNeX** [comment] 2019-06-20 23:54
I can confirm this issue; @tim-savage is this plugin still maintained?

**Comment by LickTheCheese** [comment] 2019-10-25 21:53
i also have this issue

**Comment by LickTheCheese** [comment] 2019-10-27 12:07
However, it appears that if you disable signs, it will no longer dupe the items.

Possibly the plugin crashing when it tries to place a sign and then not deleting the items?

[here are some relevant logs](https://paste.tildeverse.org/?bce31f2b4f710398#2qFm5G6c4QuUUTP7UqPPEEiYFvcQboSQK8yiHCbyZvpV)

**Comment by tim-savage** [comment] 2020-07-07 16:01
This issue was caused by material names for signs being changed in the bukkit api. Fixed in latest version.

**Closed by tim-savage** 2020-07-07 16:01 UTC
